<?php

$scriptname = $_SERVER["SCRIPT_NAME"];
$scriptfilename = $_SERVER["SCRIPT_FILENAME"];
$dirname = dirname($scriptfilename);
$docroot = $_SERVER["DOCUMENT_ROOT"];
$homepage = (strcmp($docroot, $dirname) == 0);
$debug = $_REQUEST["debug"];
$hidden = $_REQUEST["hidden"];

#############################################################################################

function DIV($id= NULL, $contentvalue = NULL)
{
  if (is_null($id) or is_null($contentvalue) or is_numeric($contentvalue))
    if (!is_null($contentvalue) and $contentvalue)
      return "<DIV ID=\"" . $id. "\">\n";
    else
      return "</DIV>\n";
  else
    return "<DIV ID=\"" . $id. "\">\n" . $contentvalue . "</DIV>\n";
}

function H($level, $header)
{
  return "<H" . $level . ">" . $header . "</H" . $level . ">\n";
}

function P($paragraph)
{
  return "<P>" . $paragraph . "</P>\n";
}

function B($paragraph, $newline = true)
{
  return "<B>" . $paragraph . "</B>" . ($newline ? "\n" : "");
}

function HR()
{
  return "<HR>\n";
}

function BR()
{
  return "<BR>\n";
}

function HREF($text, $link, $target = NULL, $newline = true, $active = true)
{
  if ($active)
    if (!is_null($target) and strlen($target) > 0)
      return "<A HREF=\"" . $link . "\" TARGET=\"" . $target . "\">" . $text . "</A>" .
             ($newline ? "\n" : "");
    else
      if (strncmp($link, "http", 4) == 0 or strlen($_SERVER["QUERY_STRING"]) == 0)
        return "<A HREF=\"" . $link . "\">" . $text . "</A>" . ($newline ? "\n" : "");
      else
        return "<A HREF=\"" . $link . "?" . $_SERVER["QUERY_STRING"] . "\">" . $text . "</A>" .
               ($newline ? "\n" : "");
  else
    return $text . ($newline ? "\n" : "");
}

function UL($contentvalue)
{
  if (is_numeric($contentvalue))
    if ($contentvalue)
      return "<UL>\n";
    else
      return "</UL>\n";
  else
    return "<UL>\n" . $contentvalue . "</UL>\n";
}

function LI($tekst)
{
  return "<LI>" . $tekst . "</LI>\n";
}

function IMG($path)
{
  return "<IMG SRC=\"" . $path . "\">\n";
}

function TABLE($contentvalue)
{
  if (is_numeric($contentvalue))
    if ($contentvalue)
      return "<TABLE>\n";
    else
      return "</TABLE>\n";
  else
    return "<TABLE>\n" . $contentvalue . "</TABLE>\n";
}

function TR($contentvalue)
{
  if (is_numeric($contentvalue))
    if ($contentvalue)
      return "<TR>\n";
    else
      return "</TR>\n";
  else
    return "<TR>\n" . $contentvalue . "</TR>\n";
}

function TD($contentvalue)
{
  if (is_numeric($contentvalue))
    if ($contentvalue)
      return "<TD>\n";
    else
      return "</TD>\n";
  else
    return "<TD>\n" . $contentvalue . "</TD>\n";
}

#############################################################################################

function cms_control($scriptfilename)
{
  #define(TITLE, "<?php #");
  $header = array(-1, "X", htmlspecialchars("(Undefined)"));

  if (is_file($scriptfilename)) {
    $handle = fopen($scriptfilename, "r");
    $control = fgets($handle);
    fclose($handle);
    if (ereg("<\?php +# +([0-9]+)([\*\+\-\?\!])(.*)", $control, $regs)) {
      $header = array($regs[1], $regs[2], htmlspecialchars($regs[3]));
    }
  }

  return $header;
}

#############################################################################################

function cms($indhold)
{
  global $scriptname, $scriptfilename, $docroot, $dirname, $homepage, $debug, $hidden;

  $control = cms_control($scriptfilename);
?>
<!DOCTYPE HTML><!--  PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" -->
<HTML>
<HEAD>

<TITLE><?=$control[2]; ?></TITLE>

<META content="text/html; charset=windows-1252" http-equiv=Content-Type></HEAD>
<META NAME="Description" CONTENT="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX">
<META NAME="Keywords" CONTENT="Birgith Weber Design">

<META NAME="AUTHOR" CONTENT="Andrew Rump">
<META NAME="GENERATOR" CONTENT="Automagically generated by Andrew Rump!">
<META NAME="TIMESTAMP" CONTENT="<?= date("F d, Y H:i:s"); ?>">
<META NAME="COPYRIGHT" CONTENT="Copyright: © 2012 Andrew Rump">

<STYLE>
/*HR {color:sienna;}*/
H1 { font-style: italic; }
H2 { font-style: italic; }
H3 { font-style: italic; }
H4 { font-style: italic; }
H5 { font-style: italic; }
H6 { font-style: italic; }
P { font-style: italic; font-size: 15}
LI { font-style: italic; }
/*P {margin-left:20px;}*/
/*body {background-image:url("images/back40.gif");}*/
body {
color:white;
background-color:black;
}
#galleria{ width: 700px; height: 400px; background: #000 }
</STYLE>

<META HTTP-EQUIV="Window-target" CONTENT="_top"> 
<SCRIPT LANGUAGE="javascript" TYPE="text/javascript">
<!-- Hide script from older browsers so it doesn't show it
if(top != self)
  {top.location = self.location;}
// The above script get the page out of frames -->
</SCRIPT>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
<script src="/include/galleria/galleria-1.2.8.min.js"></script>

</HEAD>
<BODY>
<?php
print DIV("header", 1);
print UL(1);

if (!$homepage) {
  if ($hDir = opendir($dirname . "/..")) {
    while (($entry = readdir($hDir)) !== false) {
      $control = cms_control( "../" . $entry);
      if (is_dir("../" . $entry) and $entry[0] != '.') {
        if (strcmp($control[1], "*") == 0 or $hidden and strcmp($control[1], "-") == 0 ) {
          print LI(HREF($control[2], "../" . $entry, NULL, false));
        }
      } else {
        if (is_file("../" . $entry)) {# and strncmp(strrev($entry) == 0) {
          if (strcmp($control[1], "*") == 0 or $hidden and strcmp($control[1], "-") == 0 ) {
            print LI(HREF($control[2], "../" . $entry, NULL, false));
          }
        }
      }
    }
  }
  closedir($hDir);
}
# BUG Only works one level up. Need to be made dynamic
if ($hDir = opendir($dirname)) {
  while (($entry = readdir($hDir)) !== false) {
    if (is_dir($entry) and $entry[0] != '.') {
      $control = cms_control($entry . "/index.php");
      if (strcmp($control[1], "*") == 0 or $hidden and strcmp($control[1], "-") == 0 ) {
        print LI(HREF($control[2], $entry, NULL, false));
      }
    } else {
      if (is_file($entry)) {# and strncmp(strrev($entry) == 0) {
        $control = cms_control($entry);
        if (strcmp($control[1], "*") == 0 or $hidden and strcmp($control[1], "-") == 0 ) {
          print LI(HREF($control[2], $entry, NULL, false, strcmp($entry, $scriptname) == 0));
        }
      }
    }
  }
  closedir($hDir);
}

print UL(0);
print DIV();

print BR();
?>

<!-- http://galleria.io/ -->
<div id="galleria">
<?php
if ($hDir = opendir($docroot)) {
  while (($entry = readdir($hDir)) !== false) {
    if (is_file($docroot . "/" . $entry)) {
      $parts = explode(".", $entry);
      if (is_array($parts) && count($parts) > 1) {
        $ext = strtolower(end($parts));
        if (strcmp($ext, "jpg") == 0)
          print IMG("/" . $entry);
      }
    }
  }
  closedir($hDir);
}
if ($hDir = opendir($docroot . "/Images/")) {
  while (($entry = readdir($hDir)) !== false) {
    if (is_file($docroot . "/Images/" . $entry)) {
      $parts = explode(".", $entry);
      if (is_array($parts) && count($parts) > 1) {
        $ext = strtolower(end($parts));
        if (strcmp($ext, "jpg") == 0)
          print IMG("/Images/" . $entry);
      }
    }
  }
  closedir($hDir);
}
?>
</div>

<script>
Galleria.loadTheme('/include/galleria/themes/classic/galleria.classic.min.js');
Galleria.run('#galleria', {
  autoplay: 7000 // will move forward every 7 seconds
});
//var gallery = Galleria.get(0);
//gallery.play();
</script>

<?php
print DIV("content", $indhold);

print HR();

print DIV("footer", P("Copyright: &copy; 2012 " . HREF("Weber Design", "#top", NULL, false)));

if ($debug)
  phpinfo();
?>
<!--
<script>
    $("body").text("jQuery works");
</script>
-->
</BODY>
</HTML>
<?php
}
?>