<?php

$scriptname = $_SERVER["SCRIPT_NAME"];
$scriptfilename = $_SERVER["SCRIPT_FILENAME"];
$dirname = dirname($scriptfilename);
$homepage = (strcmp($_SERVER["DOCUMENT_ROOT"], $dirname) == 0);
$debug = $_REQUEST["debug"];
$hidden = $_REQUEST["hidden"];

#############################################################################################

function DIV($contentvalue, $id)
{
  if (is_numeric($contentvalue))
    if ($contentvalue)
      return "<DIV ID=\"" . $id . "\">\n";
    else
      return "</DIV>\n";
  else
    return "<DIV ID =\"" . $id . "\">\n" . $contentvalue . "</DIV>\n";
}

function H($level, $header)
{
  return "<H" . $level . ">" . $header . "</H" . $level . ">\n";
}

function P($paragraph)
{
  return "<P>" . $paragraph . "</P>\n";
}

function B($paragraph, $newline = true)
{
  return "<B>" . $paragraph . "</B>" . ($newline ? "\n" : "");
}

function HR()
{
  return "<HR>\n";
}

function BR()
{
  return "<BR>\n";
}

function HREF($text, $link, $target = "", $newline = true, $active = true)
{
  if ($active)
    if (strlen($target) > 0)
      return "<A HREF=\"" . $link . "\" TARGET=\"" . $target . "\">" . $text . "</A>" .
             ($newline ? "\n" : "");
    else
      if (strncmp($link, "http", 4) == 0 or strlen($_SERVER["QUERY_STRING"]) == 0)
        return "<A HREF=\"" . $link . "\">" . $text . "</A>" . ($newline ? "\n" : "");
      else
        return "<A HREF=\"" . $link . "?" . $_SERVER["QUERY_STRING"] . "\">" . $text . "</A>" .
               ($newline ? "\n" : "");
  else
    return $text . ($newline ? "\n" : "");
}

function UL($contentvalue)
{
  if (is_numeric($contentvalue))
    if ($contentvalue)
      return "<UL>\n";
    else
      return "</UL>\n";
  else
    return "<UL>\n" . $contentvalue . "</UL>\n";
}

function LI($tekst)
{
  return "<LI>" . $tekst . "</LI>\n";
}

#############################################################################################

function cms_control($scriptfilename)
{
  #define(TITLE, "<?php #");
  $header = array(-1, "X", htmlspecialchars("(Undefined)"));

  if (is_file($scriptfilename)) {
    $handle = fopen($scriptfilename, "r");
    $control = fgets($handle);
    fclose($handle);
    if (ereg("<\?php +# +([0-9]+)([\*\+\-\?\!])(.*)", $control, $regs)) {
      $header = array($regs[1], $regs[2], htmlspecialchars($regs[3]));
    }
  }

  return $header;
}

#############################################################################################

function cms($indhold)
{
  global $scriptname, $scriptfilename, $dirname, $homepage, $debug, $hidden;

  $control = cms_control($scriptfilename);
?>
<!DOCTYPE HTML><!--  PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" -->
<HTML>
<HEAD>

<TITLE><?=$control[2]; ?></TITLE>

<META content="text/html; charset=windows-1252" http-equiv=Content-Type></HEAD>
<META NAME="Description" CONTENT="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX">
<META NAME="Keywords" CONTENT="Birgith Weber Design">

<META NAME="AUTHOR" CONTENT="Andrew Rump">
<META NAME="GENERATOR" CONTENT="Automagically generated by Andrew Rump!">
<META NAME="TIMESTAMP" CONTENT="<?= date("F d, Y H:i:s"); ?>">
<META NAME="COPYRIGHT" CONTENT="Copyright: © 2012 Andrew Rump">

<STYLE>
HR {color:sienna;}
/*P {margin-left:20px;}*/
/*body {background-image:url("images/back40.gif");}*/
body {
color:white;
background-color:black;
}
</STYLE>

<META HTTP-EQUIV="Window-target" CONTENT="_top"> 
<SCRIPT LANGUAGE="javascript" TYPE="text/javascript">
<!-- Hide script from older browsers so it doesn't show it
if(top != self)
  {top.location = self.location;}
// The above script get the page out of frames -->
</SCRIPT>

</HEAD>
<BODY>

<!--
<UL><LI>
<A NAME="top">
<?php if (!$homepage) { ?>
  <A HREF="/">
<?php } ?>
Weber Design
<?php if (!$homepage) { ?>
  </A>
<?php } ?>
</A>
-->

<?php

print DIV(1, "header");
print UL(1);

#print LI(HREF("Weber Design", "/index1.php", "", false, !$homepage));

if (!$homepage) {
  if ($hDir = opendir($dirname . "/..")) {
    while (($entry = readdir($hDir)) !== false) {
      $control = cms_control( "../" . $entry);
      if (is_dir("../" . $entry) and $entry[0] != '.') {
        if (strcmp($control[1], "*") == 0 or $hidden and strcmp($control[1], "-") == 0 ) {
          print LI(HREF($control[2], "../" . $entry, "", false));
        }
      } else {
        if (is_file("../" . $entry)) {# and strncmp(strrev($entry) == 0) {
          if (strcmp($control[1], "*") == 0 or $hidden and strcmp($control[1], "-") == 0 ) {
            print LI(HREF($control[2], "../" . $entry, "", false));
          }
        }
      }
    }
  }
  closedir($hDir);
}
# BUG Only works one level up. Need to be made dynamic
if ($hDir = opendir($dirname)) {
  while (($entry = readdir($hDir)) !== false) {
    if (is_dir($entry) and $entry[0] != '.') {
      $control = cms_control($entry . "/index.php");
      if (strcmp($control[1], "*") == 0 or $hidden and strcmp($control[1], "-") == 0 ) {
        print LI(HREF($control[2], $entry, "", false));
      }
    } else {
      if (is_file($entry)) {# and strncmp(strrev($entry) == 0) {
        $control = cms_control($entry);
#print LI($control[0] . $entry . $control[1] . $control[2]);
        if (strcmp($control[1], "*") == 0 or $hidden and strcmp($control[1], "-") == 0 ) {
          print LI(HREF($control[2], $entry, "", false, strcmp($entry, $scriptname) == 0));
        }
      }
    }
  }
  closedir($hDir);
}

print UL(0);
print DIV(0);

print BR();

print DIV($indhold, "content");

print HR();
?>

<DIV ID="footer">
<P ALIGN=CENTER>
Copyright: &copy; 2012
<?php if ($homepage) { ?>
  <A HREF="#top" TITLE="Weber Design">Weber Design</A>.
<?php } else { ?>
  <A HREF="/" TITLE="Weber Design">Weber Design</A>
<?php } ?>
</P>
</DIV>

<?php
if ($debug)
  phpinfo();
?>

</BODY>
</HTML>

<?php
}
?>